src/main/webapp/i18n/pt-pt/drug.json

Updated translation from "Aviso" to "Observação"

MSEDO-204: Wrong label name in medicine

---

src/main/webapp/app/layouts/navbar/navbar.component.html

MSEDO-209: Toxicity Rate option should not appears in the menu

---

src/main/webapp/app/layouts/navbar/navbar.component.html

Removed application version from navbar

MSEDO-207: Weird snapshot label in header

---

src/main/webapp/content/scss/global.scss
src/main/webapp/i18n/en/global.json
src/main/webapp/i18n/pt-pt/global.json

MSEDO-208: Weird footer in the app

---

.github/workflows/github-ci.yml

QA environment URL: https://supportivecare-qa.herokuapp.com
PROD environment URL: https://supportivecare.herokuapp.com

MSEDO-214: Setup different environments (QA and Prod)

---

src/main/webapp/app/app.module.ts
src/main/webapp/app/entities/drug/drug-detail.component.html
src/main/webapp/app/entities/drug/drug.component.html
src/main/webapp/app/entities/symptom/symptom-detail.component.html
src/main/webapp/app/entities/symptom/symptom.component.html
src/main/webapp/app/entities/therapeutic-regime/therapeutic-regime-detail.component.html
src/main/webapp/app/entities/therapeutic-regime/therapeutic-regime.component.html
src/main/webapp/app/layouts/main/main.component.html
src/main/webapp/app/layouts/main/main.component.ts
src/main/webapp/app/layouts/main/main.scss
src/main/webapp/app/layouts/navbar/navbar.component.html
src/main/webapp/app/login/login.component.html
src/main/webapp/app/login/login.component.ts
src/main/webapp/app/login/login.scss
src/main/webapp/index.html
src/test/javascript/cypress/integration/account/login-page.spec.ts
src/test/javascript/cypress/integration/account/password-page.spec.ts
src/test/javascript/cypress/integration/account/register-page.spec.ts
src/test/javascript/cypress/integration/account/reset-password-page.spec.ts
src/test/javascript/cypress/integration/entity/drug.spec.ts
src/test/javascript/cypress/integration/entity/treatment.spec.ts
src/test/javascript/cypress/support/commands.ts
src/test/javascript/cypress/support/navbar.ts
src/test/javascript/spec/app/entities/therapeutic-regime/therapeutic-regime-cancel-dialog.component.spec.ts
src/test/javascript/spec/app/layouts/main/main.component.spec.ts
src/test/javascript/spec/app/login/login.component.spec.ts

Related with feature MSEDO-174

MSEDO-227: [feat] Add login page

---

src/main/webapp/app/account/password/password-strength-bar.component.ts
src/main/webapp/app/account/password/password-strength-bar.scss
src/main/webapp/app/account/register/register.component.html
src/main/webapp/app/account/register/register.component.ts
src/main/webapp/app/account/register/register.scss
src/main/webapp/app/login/login.component.html
src/main/webapp/app/login/login.scss
src/main/webapp/content/scss/global.scss
src/main/webapp/i18n/en/global.json
src/main/webapp/i18n/pt-pt/global.json
src/test/javascript/spec/app/entities/therapeutic-regime/therapeutic-regime-update.component.spec.ts

MSEDO-175: [feat] improve register page

---

src/main/webapp/app/entities/drug/drug.component.html
src/main/webapp/app/entities/symptom/symptom.component.html
src/main/webapp/app/entities/therapeutic-regime/therapeutic-regime.component.html

- **New features that are going to be developed related to lists should use the same solution as here**

MSEDO-244 - buttons should be clickable

---

src/main/webapp/app/account/register/register.component.html
src/main/webapp/app/admin/user-management/user-management.component.html
src/main/webapp/i18n/en/register.json
src/main/webapp/i18n/pt-pt/register.json

MSEDO-257
- On this PR I changed the registration success message to be more user friendly;
- Checked the user registration is created ✅
- @xalves it would be nice to start to create the user creation page so that the user understands that for creating an account, they need to be accepted by an administrator on the user management page.

MSEDO-257: [chore] correct register flow

---

src/main/webapp/app/entities/drug/drug-detail.component.html
src/main/webapp/content/scss/global.scss

- When checking this please test functionality on the UI

MSEDO-211 - Collapsable in medicines isn't all clickable

---

src/main/webapp/app/entities/outcome/delete/outcome-delete-dialog.component.html
src/main/webapp/app/entities/outcome/delete/outcome-delete-dialog.component.ts
src/main/webapp/app/entities/outcome/detail/outcome-detail.component.html
src/main/webapp/app/entities/outcome/detail/outcome-detail.component.spec.ts
src/main/webapp/app/entities/outcome/detail/outcome-detail.component.ts
src/main/webapp/app/entities/outcome/list/outcome.component.ts
src/main/webapp/content/scss/global.scss
src/main/webapp/i18n/en/outcome.json
src/main/webapp/i18n/pt-pt/global.json
src/main/webapp/i18n/pt-pt/outcome.json

- Delete from DB is dependent from feature MSEDO-180 Creat/Edit task.
- ~~Delete is applied for now on the list but when MSEDO-262 is completed should be applied inside details page.~~
- ~~Coverage will be 100% when MSEDO-179 is completed because delete method will be removed from outcome component and delete method on outcome.component.ts will not exist anymore.~~
- ~~Rebase done on MSEDO-262 in order to complete tests for modal, once both PR are approved I will rebase MSEDO-262 in this one to get the tests for the modal and we can merge only one of them or both becuase both branches will have same changes.~~

MSEDO-181 - Delete PROM

---

src/main/java/uc/dei/mse/supportivecare/service/OutcomeService.java
src/main/java/uc/dei/mse/supportivecare/web/rest/OutcomeResource.java
src/main/webapp/app/entities/outcome/service/outcome.service.ts
src/main/webapp/app/entities/outcome/update/outcome-update.component.html
src/main/webapp/app/entities/outcome/update/outcome-update.component.spec.ts
src/main/webapp/app/entities/outcome/update/outcome-update.component.ts
src/main/webapp/app/entities/outcome/update/updateOutcome.scss
src/main/webapp/content/scss/global.scss

fix: changes to accomodate files changes on edition (MSEDO-319)

---

src/main/java/uc/dei/mse/supportivecare/domain/Outcome.java
src/main/java/uc/dei/mse/supportivecare/service/OutcomeService.java
src/main/java/uc/dei/mse/supportivecare/service/dto/OutcomeDTO.java
src/main/resources/config/liquibase/changelog/20210112214900_added_link_field_Outcome.xml
src/main/resources/config/liquibase/master.xml
src/main/webapp/app/entities/outcome/detail/outcome-detail.component.html
src/main/webapp/app/entities/outcome/detail/outcome-detail.component.ts
src/main/webapp/app/entities/outcome/outcome.model.ts
src/main/webapp/app/entities/outcome/update/outcome-update.component.html
src/main/webapp/app/entities/outcome/update/outcome-update.component.ts
src/main/webapp/i18n/en/outcome.json
src/main/webapp/i18n/pt-pt/outcome.json
supportivecare.jdl

MSEDO-330: add link field to prom (chore)

---

src/main/webapp/app/entities/active-substance/detail/active-substance-detail.component.html
src/main/webapp/app/entities/symptom/detail/symptom-detail.component.html

- Fixed issues with id's that prevented the panel from closing

MSEDO-211 - Collapsible in medicines/Symptoms isn't all clickable

---

src/main/webapp/app/entities/document/service/document.service.spec.ts
src/main/webapp/app/entities/feedback/define-reason/define-reason-dialog.component.spec.ts
src/main/webapp/app/entities/therapeutic-regime/update/therapeutic-regime-update.component.spec.ts
src/main/webapp/app/layouts/navbar/navbar.component.spec.ts
src/test/javascript/cypress/integration/account/login-page.spec.ts
src/test/javascript/cypress/integration/account/password-page.spec.ts
src/test/javascript/cypress/integration/account/register-page.spec.ts
src/test/javascript/cypress/integration/entity/administration.spec.ts
src/test/javascript/cypress/integration/entity/feedback.spec.ts
src/test/javascript/cypress/integration/entity/outcome.spec.ts
src/test/javascript/cypress/integration/entity/symptom.spec.ts
src/test/javascript/cypress/integration/entity/therapeutic-regime.spec.ts

MSEDO-358: add manual testing traceability

---

src/main/webapp/app/entities/symptom/cancel/symptom-cancel-dialog.component.html
src/main/webapp/app/entities/symptom/cancel/symptom-cancel-dialog.component.spec.ts
src/main/webapp/app/entities/symptom/cancel/symptom-cancel-dialog.component.ts
src/main/webapp/app/entities/symptom/symptom.module.ts
src/main/webapp/app/entities/symptom/update/symptom-update.component.html
src/main/webapp/app/entities/symptom/update/symptom-update.component.spec.ts
src/main/webapp/app/entities/symptom/update/symptom-update.component.ts
src/main/webapp/app/layouts/main/main.component.scss
src/main/webapp/i18n/en/symptom.json
src/main/webapp/i18n/en/therapeuticRegime.json
src/main/webapp/i18n/pt-pt/symptom.json
src/main/webapp/i18n/pt-pt/therapeuticRegime.json
src/main/webapp/index.html

chore: fix minor defects (MSEDO-376)

---

src/main/webapp/app/home/home.component.html
src/main/webapp/app/home/home.component.scss
src/main/webapp/i18n/en/home.json
src/main/webapp/i18n/pt-pt/home.json

MSEDO-378: added active substances in home page (feat)

---

src/main/webapp/app/entities/active-substance/detail/active-substance-detail.component.html
src/main/webapp/app/entities/outcome/detail/outcome-detail.component.html
src/main/webapp/app/entities/symptom/detail/symptom-detail.component.html
src/main/webapp/app/entities/therapeutic-regime/detail/therapeutic-regime-detail.component.html
src/main/webapp/i18n/en/activeSubstance.json
src/main/webapp/i18n/en/outcome.json
src/main/webapp/i18n/en/symptom.json
src/main/webapp/i18n/en/therapeuticRegime.json
src/main/webapp/i18n/pt-pt/activeSubstance.json
src/main/webapp/i18n/pt-pt/outcome.json
src/main/webapp/i18n/pt-pt/symptom.json
src/main/webapp/i18n/pt-pt/therapeuticRegime.json

fix: change go back on details page (MSEDO-417)

---

src/main/webapp/app/entities/active-substance/detail/active-substance-detail.component.html
src/main/webapp/app/entities/outcome/detail/outcome-detail.component.html
src/main/webapp/app/entities/symptom/detail/symptom-detail.component.html
src/main/webapp/app/entities/therapeutic-regime/detail/therapeutic-regime-detail.component.html

MSEDO-422: place a "-" when empty field (fix)

---

src/main/webapp/app/entities/outcome/update/outcome-update.component.ts

MSEDO-421: create PROM with no labels (fix)

---

src/main/webapp/app/entities/active-substance/update/active-substance-update.component.html
src/main/webapp/app/entities/outcome/update/outcome-update.component.html
src/main/webapp/app/entities/symptom/update/symptom-update.component.html
src/main/webapp/app/entities/therapeutic-regime/update/therapeutic-regime-update.component.html
src/main/webapp/content/scss/global.scss

MSEDO-426: standardize buttons (fix)

---

src/main/webapp/i18n/en/activeSubstance.json
src/main/webapp/i18n/pt-pt/activeSubstance.json

MSEDO-428: remove id from active substances messages (fix)

---

src/main/webapp/app/account/settings/cancel/settings-cancel-dialog.component.html
src/main/webapp/app/entities/active-substance/delete/active-substance-delete-dialog.component.html
src/main/webapp/app/entities/feedback/delete/feedback-delete-dialog.component.html
src/main/webapp/app/entities/outcome/cancel/outcome-cancel-dialog.component.html
src/main/webapp/app/entities/outcome/delete/outcome-delete-dialog.component.html
src/main/webapp/app/entities/symptom/cancel/symptom-cancel-dialog.component.html
src/main/webapp/app/entities/symptom/delete/symptom-delete-dialog.component.html
src/main/webapp/app/entities/therapeutic-regime/cancel/therapeutic-regime-cancel-dialog.component.html
src/main/webapp/app/entities/therapeutic-regime/delete/therapeutic-regime-delete-dialog.component.html
src/main/webapp/content/scss/global.scss
src/main/webapp/i18n/en/activeSubstance.json
src/main/webapp/i18n/pt-pt/activeSubstance.json
src/main/webapp/i18n/pt-pt/symptom.json

MSEDO-427: delete/cancel popups refactor (fix)

---

src/main/webapp/app/entities/active-substance/active-substance.module.ts
src/main/webapp/app/entities/active-substance/cancel/active-substance-cancel-dialog.component.html
src/main/webapp/app/entities/active-substance/cancel/active-substance-cancel-dialog.component.spec.ts
src/main/webapp/app/entities/active-substance/cancel/active-substance-cancel-dialog.component.ts
src/main/webapp/app/entities/active-substance/update/active-substance-update.component.html
src/main/webapp/app/entities/active-substance/update/active-substance-update.component.ts

MSEDO-430: add modal when cancel active substance update (fix)

---

src/main/webapp/app/entities/symptom/update/symptom-update.component.html
src/main/webapp/app/entities/symptom/update/symptom-update.component.spec.ts
src/main/webapp/app/entities/symptom/update/symptom-update.component.ts
src/main/webapp/app/entities/therapeutic-regime/update/therapeutic-regime-update.component.html
src/main/webapp/app/entities/therapeutic-regime/update/therapeutic-regime-update.component.spec.ts
src/main/webapp/app/entities/therapeutic-regime/update/therapeutic-regime-update.component.ts

Added same fix to all dropdowns in the application

MSEDO-436 - [DEFECT] Can't associate active substances when creating therapeutic regimes
